### Список категорий
GET http://localhost:3000/api/category
Accept: application/json

### Поиск
GET http://localhost:3000/api/search?query=советскую

### Запрашивает все объявления
GET http://localhost:3000/api/offers

### Запрашивает объявление с идентификатором :id
GET http://localhost:3000/api/offers/BSN-QX

### Удаление объявления с идентификатором :id
DELETE http://localhost:3000/api/offers/hE9b4-

### Добавление нового объявления
POST http://localhost:3000/api/offers
Content-Type: application/json

{
  "category": ["Разное"],
  "description": "При покупке с меня бесплатная доставка в черте города. Две страницы заляпаны свежим кофе. Пользовались бережно и только по большим праздникам., Бонусом отдам все аксессуары.",
  "picture": "item03.jpg",
  "title": "Продам новую приставку Sony Playstation 5.",
  "price": 42698,
  "type": "OFFER"
}

### Обновление объявления
PUT http://localhost:3000/api/offers/BSN-QX
Content-Type: application/json

{
  "category": ["Авто"],
  "description": "При покупке с меня бесплатная доставка в черте города. Две страницы заляпаны свежим кофе. Пользовались бережно и только по большим праздникам., Бонусом отдам все аксессуары.",
  "picture": "item03.jpg",
  "title": "Новый заголовок",
  "price": 900,
  "type": "OFFER"
}

### Список комментариев
GET http://localhost:3000/api/offers/BSN-QX/comments

### Удаляет комментарий
DELETE http://localhost:3000/api/offers/BSN-QX/comments/pKoBeD

### Добавляет новый комментарий к публикации
POST http://localhost:3000/api/offers/BSN-QX/comments
Content-Type: application/json

{
  "text": "Это новый комментарий"
}